--[[
    AlanTooltipCompat — BG3SE Lua bootstrap (CLIENT) — v4

    Two-cache architecture (2026-05-18):
      vanilla_cache.lua   — pre-baked by the mod author, SHIPS INSIDE THE PAK.
                            Loaded via Ext.Require (Lua table format because
                            Ext.IO.LoadFile cannot read from pak data — only
                            from %LocalAppData%\Larian\BG3\Script Extender\).
                            Covers Larian's base-game items; rare regenerate
                            (only when Larian patches the game).

      compat_cache.json   — user-generated by the sidecar, lives in the user's
                            Script Extender folder. Covers the user's installed
                            mods. Regenerated by run_all.bat whenever the user
                            adds/removes mods.

    At runtime we read BOTH and merge. User cache entries WIN collisions, so
    a mod that replaces a vanilla item's compat coverage takes priority.

    Design v3 logic (unchanged): for each item, read its original Description
    handle text via Ext.Loca.GetTranslatedString, append "Compatible Bodies: ...",
    write back via Ext.Loca.UpdateTranslatedString. Dedupe by handle. Idempotent
    via marker-substring check.
--]]

local MOD_NAME = "AlanTooltipCompat"
local USER_CACHE_PATH = "AlanTooltipCompat/compat_cache.json"  -- relative to SE folder
-- BG3SE's Ext.Require does NOT auto-append .lua. Without the extension, BG3SE
-- emits "Script file could not be opened: ...ScriptExtender/Lua/vanilla_cache"
-- and Ext.Require returns nil — silently breaking vanilla item coverage.
-- Confirmed by the install_diagnostic_probe.bat code comment (which uses the
-- .lua-suffixed name for its own require) and by the 2026-05-22 BG3SE log.
-- Symptom of the broken form: in-game vanilla items show description but no
-- "Compatible Bodies: ..." line, while modded items still work normally.
local VANILLA_REQUIRE = "vanilla_cache.lua"                     -- Ext.Require name (must include .lua)
local APPEND_PREFIX = "\n\nCompatible Bodies: "
local APPEND_SUFFIX = ""
-- Hardcoded for now. If we autodetect game patch later, compare against this.
local EXPECTED_PATCH = "patch_8_hotfix_8"

local function log(msg)
    Ext.Utils.Print("[" .. MOD_NAME .. "] " .. tostring(msg))
end

-- ----------------------------------------------------------------------------
-- Cache loaders
-- ----------------------------------------------------------------------------

-- Vanilla cache MUST be loaded at bootstrap-load time, not from inside the
-- StatsLoaded callback. Ext.Require() with a single arg uses the "currently
-- loading mod" context — which only exists while a bootstrap is executing.
-- Once the bootstrap returns and the event handler later fires, the context
-- is gone and the call errors with "current mod UUID is not known".
--
-- So we Require here at module load, stash the result in an upvalue, and
-- the StatsLoaded handler just reads that upvalue.
local _vanillaCache = nil
do
    local ok, result = pcall(Ext.Require, VANILLA_REQUIRE)
    if not ok then
        log("vanilla cache load FAILED via Ext.Require('" .. VANILLA_REQUIRE
            .. "'): " .. tostring(result))
        log("  -> mod will run with user cache only (no vanilla items covered).")
    elseif type(result) ~= "table" then
        log("vanilla cache: Ext.Require returned non-table (" .. type(result) .. ")")
    else
        _vanillaCache = result
    end
end

local function loadVanillaCache()
    return _vanillaCache  -- pre-loaded upvalue; no Ext.Require call here
end

--- Load the user cache from the SE folder. Returns the parsed table or nil.
local function loadUserCache()
    local raw = Ext.IO.LoadFile(USER_CACHE_PATH, "user")
    if not raw then
        log("user cache NOT FOUND at " .. USER_CACHE_PATH)
        log("  -> run the sidecar utility to generate it.")
        return nil
    end
    local ok, parsed = pcall(Ext.Json.Parse, raw)
    if not ok or type(parsed) ~= "table" then
        log("user cache parse FAILED: " .. tostring(parsed))
        return nil
    end
    return parsed
end

local function countItems(t)
    if not t or not t.items then return 0 end
    local n = 0
    for _ in pairs(t.items) do n = n + 1 end
    return n
end

-- ----------------------------------------------------------------------------
-- Merge logic — vanilla first, user overlays (user wins collisions)
-- ----------------------------------------------------------------------------

local function mergedItems(vanilla, user)
    local out = {}
    local from_vanilla = 0
    local from_user_new = 0
    local from_user_override = 0

    if vanilla and vanilla.items then
        for tid, info in pairs(vanilla.items) do
            out[tid] = info
            from_vanilla = from_vanilla + 1
        end
    end
    if user and user.items then
        for tid, info in pairs(user.items) do
            if out[tid] ~= nil then
                from_user_override = from_user_override + 1
            else
                from_user_new = from_user_new + 1
            end
            out[tid] = info
        end
    end

    return out, from_vanilla, from_user_new, from_user_override
end

-- ----------------------------------------------------------------------------
-- Main apply loop
-- ----------------------------------------------------------------------------

local function applyAll()
    log("StatsLoaded event fired (v4 — two-cache merge).")

    local vanilla = loadVanillaCache()
    local user = loadUserCache()
    if not vanilla and not user then
        log("Both caches missing — nothing to do.")
        return
    end

    log(string.format("Caches loaded: vanilla=%d items, user=%d items.",
                      countItems(vanilla), countItems(user)))

    -- Patch-version sanity check (vanilla only; user cache regenerates often)
    if vanilla and vanilla.bg3_patch_version
            and vanilla.bg3_patch_version ~= EXPECTED_PATCH then
        log("WARNING: vanilla_cache patch version is "
            .. tostring(vanilla.bg3_patch_version)
            .. " but mod expects " .. EXPECTED_PATCH
            .. ". Newly-introduced items may not be covered.")
    end

    local merged, n_vanilla, n_user_new, n_user_override =
        mergedItems(vanilla, user)
    log(string.format("Merged: %d total (%d vanilla, %d user-new, %d user-override).",
                      n_vanilla + n_user_new, n_vanilla, n_user_new, n_user_override))

    local applied = 0
    local skipped_no_handle = 0
    local skipped_dupe_handle = 0
    local skipped_already_done = 0
    local failed_update = 0
    local seen_handles = {}
    local first_diag = true

    for templateId, info in pairs(merged) do
        local handle = info.description_handle

        if not handle or handle == "" then
            skipped_no_handle = skipped_no_handle + 1
        elseif seen_handles[handle] then
            skipped_dupe_handle = skipped_dupe_handle + 1
        else
            seen_handles[handle] = true

            local origText = Ext.Loca.GetTranslatedString(handle) or ""

            -- Diagnostic on first item only
            if first_diag then
                first_diag = false
                log("DIAGNOSTIC FIRST ITEM:")
                log("  templateId: " .. templateId)
                log("  name: " .. tostring(info.name))
                log("  handle: " .. handle)
                log("  origText.len: " .. string.len(origText))
                log("  origText[:80]: " .. string.sub(origText, 1, 80))
                log("  compat_text: " .. tostring(info.compat_text))
            end

            if string.find(origText, APPEND_PREFIX, 1, true) then
                skipped_already_done = skipped_already_done + 1
            else
                local newText = origText .. APPEND_PREFIX
                    .. (info.compat_text or "") .. APPEND_SUFFIX
                local updated = Ext.Loca.UpdateTranslatedString(handle, newText)
                if updated then
                    applied = applied + 1
                else
                    failed_update = failed_update + 1
                    if failed_update <= 3 then
                        log("  UpdateTranslatedString FAILED for handle: " .. handle)
                    end
                end
            end
        end
    end

    log(string.format("Applied: %d unique handles modified.", applied))
    if skipped_no_handle > 0 then
        log(string.format("  skipped (no handle in cache): %d", skipped_no_handle))
    end
    if skipped_dupe_handle > 0 then
        log(string.format("  skipped (handle shared w/ earlier item): %d",
                          skipped_dupe_handle))
    end
    if skipped_already_done > 0 then
        log(string.format("  skipped (already appended): %d", skipped_already_done))
    end
    if failed_update > 0 then
        log(string.format("  failed UpdateTranslatedString: %d", failed_update))
    end
end

Ext.Events.StatsLoaded:Subscribe(applyAll)
log("Bootstrap v4 loaded; waiting for StatsLoaded event.")
